development:
  clients:
    default:
      uri: mongodb+srv://root:root@cluster0-6tqp7.mongodb.net/shadowhealthquiz?retryWrites=true&w=majority
      options:
        server_selection_timeout: 10



test:
  clients:
    default:
      database: trivia_quiz_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
  raise_not_found_error: false